use crate::cpu::decoder::{decode, Inst};

pub fn disassemble(raw: u32) -> String {
    let inst = decode(raw);
    format_inst(inst)
}

pub fn format_inst(inst: Inst) -> String {
    use crate::cpu::Cpu;
    macro_rules! r { ($x:expr) => { Cpu::reg_name($x as usize) }; }

    match inst {
        Inst::Lui   { rd, imm }      => format!("lui     {}, {:#x}", r!(rd), (imm as u64) >> 12),
        Inst::Auipc { rd, imm }      => format!("auipc   {}, {:#x}", r!(rd), (imm as u64) >> 12),
        Inst::Jal   { rd, imm }      => format!("jal     {}, {:+}", r!(rd), imm),
        Inst::Jalr  { rd, rs1, imm } => format!("jalr    {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Beq   { rs1, rs2, imm }  => format!("beq     {}, {}, {:+}", r!(rs1), r!(rs2), imm),
        Inst::Bne   { rs1, rs2, imm }  => format!("bne     {}, {}, {:+}", r!(rs1), r!(rs2), imm),
        Inst::Blt   { rs1, rs2, imm }  => format!("blt     {}, {}, {:+}", r!(rs1), r!(rs2), imm),
        Inst::Bge   { rs1, rs2, imm }  => format!("bge     {}, {}, {:+}", r!(rs1), r!(rs2), imm),
        Inst::Bltu  { rs1, rs2, imm }  => format!("bltu    {}, {}, {:+}", r!(rs1), r!(rs2), imm),
        Inst::Bgeu  { rs1, rs2, imm }  => format!("bgeu    {}, {}, {:+}", r!(rs1), r!(rs2), imm),
        Inst::Lb    { rd, rs1, imm } => format!("lb      {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Lh    { rd, rs1, imm } => format!("lh      {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Lw    { rd, rs1, imm } => format!("lw      {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Ld    { rd, rs1, imm } => format!("ld      {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Lbu   { rd, rs1, imm } => format!("lbu     {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Lhu   { rd, rs1, imm } => format!("lhu     {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Lwu   { rd, rs1, imm } => format!("lwu     {}, {}({})", r!(rd), imm, r!(rs1)),
        Inst::Sb    { rs1, rs2, imm } => format!("sb      {}, {}({})", r!(rs2), imm, r!(rs1)),
        Inst::Sh    { rs1, rs2, imm } => format!("sh      {}, {}({})", r!(rs2), imm, r!(rs1)),
        Inst::Sw    { rs1, rs2, imm } => format!("sw      {}, {}({})", r!(rs2), imm, r!(rs1)),
        Inst::Sd    { rs1, rs2, imm } => format!("sd      {}, {}({})", r!(rs2), imm, r!(rs1)),
        Inst::Addi  { rd, rs1, imm } => {
            if rs1 == 0 { format!("li      {}, {}", r!(rd), imm) }
            else if imm == 0 { format!("mv      {}, {}", r!(rd), r!(rs1)) }
            else { format!("addi    {}, {}, {}", r!(rd), r!(rs1), imm) }
        }
        Inst::Slti  { rd, rs1, imm } => format!("slti    {}, {}, {}", r!(rd), r!(rs1), imm),
        Inst::Sltiu { rd, rs1, imm } => format!("sltiu   {}, {}, {}", r!(rd), r!(rs1), imm),
        Inst::Xori  { rd, rs1, imm } => format!("xori    {}, {}, {}", r!(rd), r!(rs1), imm),
        Inst::Ori   { rd, rs1, imm } => format!("ori     {}, {}, {}", r!(rd), r!(rs1), imm),
        Inst::Andi  { rd, rs1, imm } => format!("andi    {}, {}, {}", r!(rd), r!(rs1), imm),
        Inst::Slli  { rd, rs1, shamt } => format!("slli    {}, {}, {}", r!(rd), r!(rs1), shamt),
        Inst::Srli  { rd, rs1, shamt } => format!("srli    {}, {}, {}", r!(rd), r!(rs1), shamt),
        Inst::Srai  { rd, rs1, shamt } => format!("srai    {}, {}, {}", r!(rd), r!(rs1), shamt),
        Inst::Add   { rd, rs1, rs2 } => format!("add     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Sub   { rd, rs1, rs2 } => format!("sub     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Sll   { rd, rs1, rs2 } => format!("sll     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Slt   { rd, rs1, rs2 } => format!("slt     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Sltu  { rd, rs1, rs2 } => format!("sltu    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Xor   { rd, rs1, rs2 } => format!("xor     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Srl   { rd, rs1, rs2 } => format!("srl     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Sra   { rd, rs1, rs2 } => format!("sra     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Or    { rd, rs1, rs2 } => format!("or      {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::And   { rd, rs1, rs2 } => format!("and     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Addiw { rd, rs1, imm } => format!("addiw   {}, {}, {}", r!(rd), r!(rs1), imm),
        Inst::Slliw { rd, rs1, shamt } => format!("slliw   {}, {}, {}", r!(rd), r!(rs1), shamt),
        Inst::Srliw { rd, rs1, shamt } => format!("srliw   {}, {}, {}", r!(rd), r!(rs1), shamt),
        Inst::Sraiw { rd, rs1, shamt } => format!("sraiw   {}, {}, {}", r!(rd), r!(rs1), shamt),
        Inst::Addw  { rd, rs1, rs2 } => format!("addw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Subw  { rd, rs1, rs2 } => format!("subw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Sllw  { rd, rs1, rs2 } => format!("sllw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Srlw  { rd, rs1, rs2 } => format!("srlw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Sraw  { rd, rs1, rs2 } => format!("sraw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Mul    { rd, rs1, rs2 } => format!("mul     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Mulh   { rd, rs1, rs2 } => format!("mulh    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Mulhsu { rd, rs1, rs2 } => format!("mulhsu  {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Mulhu  { rd, rs1, rs2 } => format!("mulhu   {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Div    { rd, rs1, rs2 } => format!("div     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Divu   { rd, rs1, rs2 } => format!("divu    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Rem    { rd, rs1, rs2 } => format!("rem     {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Remu   { rd, rs1, rs2 } => format!("remu    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Mulw   { rd, rs1, rs2 } => format!("mulw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Divw   { rd, rs1, rs2 } => format!("divw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Divuw  { rd, rs1, rs2 } => format!("divuw   {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Remw   { rd, rs1, rs2 } => format!("remw    {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Remuw  { rd, rs1, rs2 } => format!("remuw   {}, {}, {}", r!(rd), r!(rs1), r!(rs2)),
        Inst::Ecall  => "ecall".to_string(),
        Inst::Ebreak => "ebreak".to_string(),
        Inst::Fence  => "fence".to_string(),
        Inst::Mret   => "mret".to_string(),
        Inst::Sret   => "sret".to_string(),
        Inst::Csrrw  { rd, rs1, csr }  => format!("csrrw   {}, {:#x}, {}", r!(rd), csr, r!(rs1)),
        Inst::Csrrs  { rd, rs1, csr }  => format!("csrrs   {}, {:#x}, {}", r!(rd), csr, r!(rs1)),
        Inst::Csrrc  { rd, rs1, csr }  => format!("csrrc   {}, {:#x}, {}", r!(rd), csr, r!(rs1)),
        Inst::Csrrwi { rd, uimm, csr } => format!("csrrwi  {}, {:#x}, {}", r!(rd), csr, uimm),
        Inst::Csrrsi { rd, uimm, csr } => format!("csrrsi  {}, {:#x}, {}", r!(rd), csr, uimm),
        Inst::Csrrci { rd, uimm, csr } => format!("csrrci  {}, {:#x}, {}", r!(rd), csr, uimm),
        Inst::AmoaddW { rd, rs1, rs2, aq, rl } => format!("amoadd.w{}{} {}, {}, ({})",
            if aq { ".aq" } else { "" },
            if rl { ".rl" } else { "" },
            r!(rd), r!(rs2), r!(rs1)),
        Inst::AmoswapW { rd, rs1, rs2, aq, rl } => format!("amoswap.w{}{} {}, {}, ({})",
            if aq { ".aq" } else { "" },
            if rl { ".rl" } else { "" },
            r!(rd), r!(rs2), r!(rs1)),
        Inst::LrW { rd, rs1, aq, rl } => format!("lr.w{}{} {}, ({})",
            if aq { ".aq" } else { "" },
            if rl { ".rl" } else { "" },
            r!(rd), r!(rs1)),
        Inst::ScW { rd, rs1, rs2, aq, rl } => format!("sc.w{}{} {}, {}, ({})",
            if aq { ".aq" } else { "" },
            if rl { ".rl" } else { "" },
            r!(rd), r!(rs2), r!(rs1)),
        Inst::LrD { rd, rs1, aq, rl } => format!("lr.d{}{} {}, ({})",
            if aq { ".aq" } else { "" },
            if rl { ".rl" } else { "" },
            r!(rd), r!(rs1)),
        Inst::ScD { rd, rs1, rs2, aq, rl } => format!("sc.d{}{} {}, {}, ({})",
            if aq { ".aq" } else { "" },
            if rl { ".rl" } else { "" },
            r!(rd), r!(rs2), r!(rs1)),
        Inst::Illegal(raw)             => format!("illegal {:#010x}", raw),
    }
}
